export const eventsGPS = [
  {
    id: '671e833c56827a52cc26764f',
    title: 'Антон Тимошенко',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884317/bookMyEventApp/hhgelfgsyyvzmvqahxsh.jpg',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Успішна, 1',
      venue: null,
      latitude: 50.388996,
      longitude: 30.459957,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '20 листопада',
      time: '17:00',
    },
    tickets: 10000,
    price: 700,
    type: 'Stand-up',
    category: null,
  },
  {
    id: '671e833c56827a52cc267650',
    title: 'Біжу за Азов - Молодіжний захід',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884318/bookMyEventApp/mtd548bja4bqnej3uuec.jpg',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Антоновича, 40',
      venue: null,
      latitude: 50.434331,
      longitude: 30.51315,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '10 листопада',
      time: '12:00',
    },
    tickets: 10000,
    price: 0,
    type: 'Спортивні заходи',
    category: null,
  },
  {
    id: '671e833c56827a52cc267651',
    title: 'Практикум від хаосу до системного управління',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884317/bookMyEventApp/lprkpszmaqdyqvd20xcz.jpg',
    creationDate: '2024-09-25T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Мінська, 10',
      venue: null,
      latitude: 50.490566,
      longitude: 30.436957,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '28 листопада',
      time: '17:00',
    },
    tickets: 10000,
    price: 1000,
    type: 'Бізнес та нетворкінг',
    category: null,
  },
  {
    id: '671e833c56827a52cc267652',
    title: 'Книжковий клуб',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884316/bookMyEventApp/ia05hpjbvqwrpgpaoq7q.jpg',
    creationDate: '2024-08-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Глибочицька, 6а',
      venue: null,
      latitude: 50.460291,
      longitude: 30.488216,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '1 грудня',
      time: '20:00',
    },
    tickets: 10000,
    price: 200,
    type: 'Інше',
    category: null,
  },
  {
    id: '671e833c56827a52cc267653',
    title: 'Дитячий кулінарний майстер-клас для дітей ві...',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884317/bookMyEventApp/nftwsdxpnhxghxijs767.jpg',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Ковпака, 17',
      venue: null,
      latitude: 50.417223,
      longitude: 30.524763,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '24 жовтня',
      time: '17:00',
    },
    tickets: 10000,
    price: 600,
    type: 'Майстер класи',
    category: null,
  },
  {
    id: '671e833c56827a52cc267654',
    title: 'Open air Stand-up',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884317/bookMyEventApp/bexkb2uidtcsml3lo3pl.jpg',
    creationDate: '2024-10-10T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Ананасна, 5',
      venue: 'Маріїнський парк',
      latitude: 50.488873,
      longitude: 30.404809,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '18 листопада',
      time: '14:00',
    },
    tickets: 10000,
    price: 0,
    type: 'Stand-up',
    category: null,
  },
  {
    id: '671e833c56827a52cc267655',
    title: 'Забіг із собаками',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884317/bookMyEventApp/pclvrfqg0qcz3gwcabwu.jpg',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Серпова, 50',
      venue: null,
      latitude: 50.460732,
      longitude: 30.372459,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '12 листопада',
      time: '13:00',
    },
    tickets: 10000,
    price: 500,
    type: 'Спортивні заходи',
    category: null,
  },
  {
    id: '671e833c56827a52cc267656',
    title: 'Blyskavytsia у сутінках',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884317/bookMyEventApp/r2mhwelxzz9vvlksr5fq.jpg',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Академіка Баха, 3',
      venue: null,
      latitude: 50.44798,
      longitude: 30.610722,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '30 жовтня',
      time: '17:00',
    },
    tickets: 10000,
    price: 300,
    type: 'Інше',
    category: null,
  },
  {
    id: '671e833c56827a52cc267657',
    title: '50 відтінків Product Manager',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884317/bookMyEventApp/nbtyykzniqkbqswek1wd.jpg',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Антоновича, 83',
      venue: null,
      latitude: 50.425431,
      longitude: 30.51568,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '12 вересня',
      time: '17:00',
    },
    tickets: 10000,
    price: 1000,
    type: 'Бізнес та нетворкінг',
    category: null,
  },
  {
    id: '671e833c56827a52cc267658',
    title: 'Емо Проблема Party',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884315/bookMyEventApp/mkdgvjj52rxqqn9xjcy8.png',
    creationDate: '2024-05-12T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Антоновича, 74',
      venue: null,
      latitude: 50.426129,
      longitude: 30.514067,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '12 вересня',
      time: '20:00',
    },
    tickets: 10000,
    price: 600,
    type: 'Інше',
    category: null,
  },
  // {
  //   id: '671e833c56827a52cc267659',
  //   title: 'Тренди Твіттера',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1729884315/bookMyEventApp/nj7bvpt7kzq8renys6sv.png',
  //   creationDate: '2024-10-20T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Аніщенко, 10г',
  //     venue: null,
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '23 жовтня',
  //     time: '17:00',
  //   },
  //   tickets: 10000,
  //   price: 500,
  //   type: 'Майстер класи',
  //   category: null,
  // },
  {
    id: '671e833c56827a52cc26765a',
    title: 'Сольний концерт YAKTAK',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1730986366/bookMyEventApp/ppskgfojzishe8apxulj.jpg',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Глибочицька, 10б',
      venue: null,
      latitude: 50.460291,
      longitude: 30.488216,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '16 листопада',
      time: '16:00',
    },
    tickets: 10000,
    price: 400,
    type: 'Концерти',
    category: null,
  },
  {
    id: '671e833c56827a52cc26765b',
    title: 'Kyiv Desion Week',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1730987744/bookMyEventApp/ab0rsfb3qxzjasyt1fbh.png',
    creationDate: '2024-07-10T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Щекавицька, 40',
      venue: null,
      latitude: 50.471728,
      longitude: 30.51512,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '12 листопада',
      time: '18:00',
    },
    tickets: 10000,
    price: 400,
    type: 'Майстер класи',
    category: null,
  },
  // {
  //   id: '671e833c56827a52cc26765c',
  //   title: 'Kler',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1729884316/bookMyEventApp/hflztgwhukigl9sor6pa.png',
  //   creationDate: '2024-10-20T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Нова Дарниця, 10',
  //     venue: null,
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '30 жовтня',
  //     time: '21:00',
  //   },
  //   tickets: 10000,
  //   price: 1000,
  //   type: 'Концерти',
  //   category: null,
  // },
  {
    id: '671e833c56827a52cc26765d',
    title: 'Благодійний турнір з міні-футболу',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884315/bookMyEventApp/lzvalxcnxq8bjl0yhjtz.png',
    creationDate: '2024-09-16T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Кіото, 3',
      venue: null,
      latitude: 50.462954,
      longitude: 30.631079,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '31 жовтня',
      time: '17:00',
    },
    tickets: 10000,
    price: 200,
    type: 'Спортивні заходи',
    category: null,
  },
  {
    id: '671e833c56827a52cc26765e',
    title: 'Вечори на хуторі біля Диканьки',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884315/bookMyEventApp/fbnmsf7jqisutrjbxs2q.png',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Академіка Баха, 12',
      venue: null,
      latitude: 50.449845,
      longitude: 30.609576,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '6 листопада',
      time: '17:00',
    },
    tickets: 10000,
    price: 900,
    type: 'Концерти',
    category: null,
  },
  {
    id: '671e833c56827a52cc26765f',
    title: 'Стендап на даху',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884314/bookMyEventApp/vln28mu8z9lw9q3wvsd5.png',
    creationDate: '2024-10-20T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Володимирська, 100',
      venue: null,
      latitude: 50.433107,
      longitude: 30.50778,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '6 листопада',
      time: '17:00',
    },
    tickets: 10000,
    price: 900,
    type: 'Stand-up',
    category: 'TOP_EVENTS',
  },
  {
    id: '671e833c56827a52cc267660',
    title: 'Max Barskih',
    description: 'An example event description',
    photoUrl:
      'https://res.cloudinary.com/dlweazskq/image/upload/v1729884314/bookMyEventApp/ex48jo5rzau0yh764dji.png',
    creationDate: '2024-10-10T10:00:00',
    phoneNumber: '+380123456789',
    numberOfTickets: 0,
    location: {
      city: 'Київ',
      street: 'вул. Уманська, 35',
      venue: 'Палац Спорту',
      latitude: 50.439658,
      longitude: 30.459073,
    },
    organizers: [
      {
        id: null,
        name: 'John Doe',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
      {
        id: null,
        name: 'Jane Smith',
        email: null,
        password: null,
        mailConfirmation: false,
        role: null,
        creationDate: null,
        phone: null,
        location: null,
        status: null,
        createdEvents: [],
      },
    ],
    rating: 4.5,
    date: {
      day: '21 грудня',
      time: '18:00',
    },
    tickets: 10000,
    price: 1000,
    type: 'Концерти',
    category: 'TOP_EVENTS',
  },
  // {
  //   id: '671e833c56827a52cc267661',
  //   title: 'Полякова',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1729884315/bookMyEventApp/ktzluqbhfwmh71qcrmg8.png',
  //   creationDate: '2024-10-29T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Абрикосна, 1б',
  //     venue: 'Палац Спорту',
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '26 листопада',
  //     time: '18:00',
  //   },
  //   tickets: 10000,
  //   price: 1000,
  //   type: 'Концерти',
  //   category: null,
  // },
  // {
  //   id: '671e833c56827a52cc267662',
  //   title: 'KIM FEST',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1729884317/bookMyEventApp/cbplu7udbkacaquvq4op.jpg',
  //   creationDate: '2024-06-25T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Сирецька, 78',
  //     venue: 'Палац Спорту',
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '10 листопада',
  //     time: '18:00',
  //   },
  //   tickets: 10000,
  //   price: 1000,
  //   type: 'Концерти',
  //   category: null,
  // },
  // {
  //   id: '671e833c56827a52cc267663',
  //   title: 'Печерські котики',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1729884314/bookMyEventApp/qnncepujpij7ssqlbfui.jpg',
  //   creationDate: '2024-10-20T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Миколи Амосова, 5',
  //     venue: 'Arena City',
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '12 жовтня',
  //     time: '16:00',
  //   },
  //   tickets: 10000,
  //   price: 0,
  //   type: 'Майстер класи',
  //   category: 'TOP_EVENTS',
  // },
  // {
  //   id: '671e833c56827a52cc267664',
  //   title: "Let’s Talk про ментальне здоров'я",
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1729884315/bookMyEventApp/wnff27fh9nr2b44kui6b.png',
  //   creationDate: '2024-10-20T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Антоновича, 50',
  //     venue: 'Arena City',
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '30 вересня',
  //     time: '12:00',
  //   },
  //   tickets: 10000,
  //   price: 1000,
  //   type: 'Бізнес та нетворкінг',
  //   category: 'TOP_EVENTS',
  // },
  // {
  //   id: '671e833c56827a52cc267665',
  //   title: 'Книжковий пікнік',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1729884316/bookMyEventApp/geofxsp5l3mbt1qdvowh.png',
  //   creationDate: '2024-10-20T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Глиба Бабіча, 1',
  //     venue: 'парк П....',
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '25 вересня',
  //     time: '19:00',
  //   },
  //   tickets: 10000,
  //   price: 0,
  //   type: 'Майстер класи',
  //   category: 'TOP_EVENTS',
  // },
  // {
  //   id: '671e833c56827a52cc267666',
  //   title: 'Благодійний концерт Jamala',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1730986357/bookMyEventApp/nmaiqvooxjkzwfptqsjm.jpg',
  //   creationDate: '2024-10-20T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Серпова, 1',
  //     venue: 'ВДНГ',
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '16 листопада',
  //     time: '16:00',
  //   },
  //   tickets: 10000,
  //   price: 0,
  //   type: 'Концерти',
  //   category: 'TOP_EVENTS',
  // },
  // {
  //   id: '671e833c56827a52cc267667',
  //   title: 'Свічки власноруч',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1730988607/bookMyEventApp/dm9honghq6nxkhbmjxze.jpg',
  //   creationDate: '2024-10-20T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Космонавтів, 50',
  //     venue: null,
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '12 вересня',
  //     time: '17:00',
  //   },
  //   tickets: 10000,
  //   price: 400,
  //   type: 'Майстер класи',
  //   category: 'TOP_EVENTS',
  // },
  // {
  //   id: '671ffa8e7efcb743c34ed1ff',
  //   title: 'The Rock SYMPHONY ORCHESTRA',
  //   description: 'An example event description',
  //   photoUrl:
  //     'https://res.cloudinary.com/dlweazskq/image/upload/v1730148702/bookMyEventApp/yi5axtzszuymvfskkpep.png',
  //   creationDate: '2024-10-20T10:00:00',
  //   phoneNumber: '+380123456789',
  //   numberOfTickets: 0,
  //   location: {
  //     city: 'Київ',
  //     street: 'вул. Велика Васильківська, 103',
  //     venue: 'Палац Спорту',
  //     latitude: ,
  //     longitude: ,
  //   },
  //   organizers: [
  //     {
  //       id: null,
  //       name: 'John Doe',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //     {
  //       id: null,
  //       name: 'Jane Smith',
  //       email: null,
  //       password: null,
  //       mailConfirmation: false,
  //       role: null,
  //       creationDate: null,
  //       phone: null,
  //       location: null,
  //       status: null,
  //       createdEvents: [],
  //     },
  //   ],
  //   rating: 4.5,
  //   date: {
  //     day: '22 листопада',
  //     time: '18:00',
  //   },
  //   tickets: 10000,
  //   price: 1000,
  //   type: 'Концерти',
  //   category: 'TOP_EVENTS',
  // },
];
